version: '3.7'

services:

  Bene-service:
    image: msu-bene-service:latest
    mem_limit: 700m
    ports:
      - "9093:9093"
    networks:
      - Bene-service-network
    depends_on:
      - service-registry

    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka

  netflix-zuul-api-gateway-server:
    image: msu-netflix-zuul-api-gateway-server:latest
    mem_limit: 700m
    ports:
      - "8765:8765"
    networks:
      - Bene-service-network
    depends_on:
      - service-registry
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://service-registry:8761/eureka
      SPRING.ZIPKIN.BASEURL: http://zipkin-server:9411/

  service-registry:
    image: msu-service-registry:latest
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - Bene-service-network

#docker run -p 9411:9411 openzipkin/zipkin:2.23

  zipkin-server:
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      - Bene-service-network

    restart: always #Restart if there is a problem starting up

networks:
  Bene-service-network: