FROM openjdk:8
ADD target/netflix-zuul-api-gateway-server-0.0.1-SNAPSHOT.jar netflix-zuul-api-gateway-server-0.0.1-SNAPSHOT.jar
EXPOSE 8765
ENTRYPOINT ["java", "-jar", "netflix-zuul-api-gateway-server-0.0.1-SNAPSHOT.jar"]